### ISSUE TITLE
Could not create a new object Kernel::System::CustomMessage!

### ISSUE THREAD

**Issue by VCSousa** [mo-azfar/OTRS-Ticket-Notification-To-MS-Teams-Channel#1]
Hi,

After configure the webhook and the queue, when testing creating the ticket (The GA are configured to execute on ticket create).

On system log i got this error:

Could not create a new object Kernel::System::CustomMessage! - Task: Recipient0.971299434325896https://outlook.office.com/webhook/ ....

**Comment by mo-azfar** [comment]
> Hi,
> 
> After configure the webhook and the queue, when testing creating the ticket (The GA are configured to execute on ticket create).
> 
> On system log i got this error:
> 
> Could not create a new object Kernel::System::CustomMessage! - Task: Recipient0.971299434325896https://outlook.office.com/webhook/ ....

This module require CustomMessage module.
Refer https://github.com/mo-azfar/OTRS-CustomMessage-API

**Comment by VCSousa** [comment]
> > Hi,
> > After configure the webhook and the queue, when testing creating the ticket (The GA are configured to execute on ticket create).
> > On system log i got this error:
> > Could not create a new object Kernel::System::CustomMessage! - Task: Recipient0.971299434325896https://outlook.office.com/webhook/ ....
> 
> This module require CustomMessage module.
> Refer https://github.com/mo-azfar/OTRS-CustomMessage-API

After putting the CustomMessage on Kernel/System, it keeps not working and give 500 error on Admin Log. It needs some configuration?

**Comment by mo-azfar** [comment]
> > > Hi,
> > > After configure the webhook and the queue, when testing creating the ticket (The GA are configured to execute on ticket create).
> > > On system log i got this error:
> > > Could not create a new object Kernel::System::CustomMessage! - Task: Recipient0.971299434325896https://outlook.office.com/webhook/ ....
> > 
> > 
> > This module require CustomMessage module.
> > Refer https://github.com/mo-azfar/OTRS-CustomMessage-API
> 
> After putting the CustomMessage on Kernel/System, it keeps not working and give 500 error on Admin Log. It needs some configuration?

Check http error log..the readme not updated yet, but there is some additional perl / cpan module require to be install..u have to check at code level (CustomMessage)

Make sure these perl package installed..(Data::Dumper not needed thought, you can comment/disable it)

use Data::Dumper;
use Fcntl qw(:flock SEEK_END);
use JSON::MaybeXS;
use LWP::UserAgent;
use HTTP::Request::Common;

**Comment by VCSousa** [comment]
Here are nothing on my httpd logs that could help. How can I install the second perlm package, i dont find anything usefull to help me
